### ISSUE TITLE
PowerPotion breaks Tutorial

### ISSUE THREAD

**Issue by P1tt187** [DigglesMods/PowerPotion#1]
Wenn man im Tutorial beim Wettkampf ist und Bier Brauen soll ist nur die Schaltfläche für die PowerPotion aktiv.  Da diese noch nicht erfunden ist und kein Zwerg die Vorausetzungen erfüllt ist die aufgabe nicht mehr Schaffbar. Einziger Workaround: Mod deaktivieren und das Tutorial neu starten.

**Comment by cech12** [comment]
Super gefunden! An sowas habe ich echt noch nie gedacht.
Ich werde mir das mal ansehen, versuchen nachzustellen und zu beheben.

**Comment by cech12** [comment]
Fehler konnte nachgestellt und behoben werden. 
Es gab einen neuen Release der Mod: https://github.com/DigglesMods/PowerPotion/releases/tag/v1.1
Wenn diese Version mit dem DigglesModManager installiert wurde und ein neues Tutorial gestartet wurde, sollte der Fehler nicht mehr auftreten.
